
export const downloadSampleReport = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const downloadPDFReport = (content: string, filename: string) => {
  // For a more PDF-like experience, we'll format the content with proper spacing and structure
  const formattedContent = `
${content}

---
Generated by Export Connect - Your Global Trade Partner
Website: www.exportconnect.com
Email: info@exportconnect.com
Phone: +91-XXX-XXX-XXXX

This is a sample report. Actual reports will be professionally formatted as PDF documents.
Confidentiality Notice: This document contains confidential and proprietary information.
`;

  const blob = new Blob([formattedContent], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
